### ISSUE TITLE
undeclared identifier 'WNOHANG'

### ISSUE THREAD

**Issue by sivers** [socketry/io-event#24]
On OpenBSD:

```
compiling ./io/event/selector/selector.c
./io/event/selector/selector.c:77:74: error: use of undeclared identifier 'WNOHANG'
        return rb_funcall(rb_Process_Status, id_wait, 2, PIDT2NUM(pid), INT2NUM(WNOHANG));
```

**Comment by ioquatix** [comment]
Hmmm, what do we need to use as an alternative?

**Comment by sivers** [comment]
Sorry, I wish I was more help. I'm just a user, and don't know C.

Seems WNOHANG should exist if #include <sys/wait.h>

https://man.openbsd.org/waitpid.2

**Comment by ioquatix** [comment]
Oh, great, I can include it.

@jeremyevans are you able to help test this? I don't have any OpenBSD systems.
