### ISSUE TITLE
doesn't build on windows

### ISSUE THREAD

**Issue by dsisnero** [socketry/io-event#46]
Any plans for windows support?

**Comment by ioquatix** [comment]
The latest version builds on Windows: https://github.com/socketry/io-event/actions/runs/3280256662/jobs/5400819481

You are going to have to be a little bit more specific with your issue/build failure.

**Comment by dsisnero** [comment]
Sorry - trying to install async which uses an older version of io-event 1.0.9 - I was able to install latest io-event.  Will move this to async gem.
