### ISSUE TITLE
warning: IO::Buffer is experimental

### ISSUE THREAD

**Issue by emiltin** [socketry/io-event#82]
Hi,
When using the async gem with Ruby 3.2.2 on macOS, I get this warning:

`/Users/emiltin/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/io-event-1.3.2/lib/io/event/support.rb:24: warning: IO::Buffer is experimental and both the Ruby and C interface may change in the future!`

This seems to come from the Ruby stdlib, but is there anyway to avoid it at the momemt?

**Comment by ioquatix** [comment]
This warning is pointing out that `io-event` could potentially break on a future version of Ruby. However, that is unlikely to occur in practice as the impact would be pretty big.

I hope to finish `IO::Buffer` by Ruby 3.3 so the warning will be removed when that happens.

In terms of removing the warning, we could probably silence it, but I suppose that defeats the purpose of the warning.

**Comment by emiltin** [comment]
Thank you for the info! I agree, silencing the warning would not be a good idea.
I was wondering if it was perhaps an issue with my installation, but I'll just leave the warning be.

**Comment by trevorturk** [comment]
FWIW I silenced with a Ruby version check so I'll remember to check again later, like so:

```ruby
Kernel.silence_warnings do
  raise("check IO::Buffer warning") unless RUBY_VERSION == "3.2.2"
  Bundler.require(*Rails.groups)
end
```

Please don't be mad at me, I know it's bad form! 😉

**Comment by kmcphillips** [comment]
A softer approach than silencing all warnings, you can suppress just the experimental ones:
```ruby
original, Warning[:experimental] = Warning[:experimental], false
Bundler.require(*Rails.groups)
Warning[:experimental] = original
```

Or use the `ruby -W:no-experimental` flag at runtime.

**Comment by ioquatix** [comment]
I think this warning isn't particularly useful, so I'm planning to avoid emitting it.

**Comment by emiltin** [comment]
Also see:

```
code/rsmp_validator (update_rsmp) % ruby -v
ruby 4.0.1 (2026-01-13 revision e04267a14b) +PRISM [x86_64-darwin22]
code/rsmp_validator (update_rsmp) % rspec spec/site
Using site config: config/gem_tlc.yaml

<internal:io>:63: warning: IO::Buffer is experimental and both the Ruby and C interface may change in the future!
```

**Comment by ioquatix** [comment]
Yes, but I will aim to finalise it for 4.1.
