### ISSUE TITLE
selector.c require include <sys/wait.h> for WNOHANG

### ISSUE THREAD

**Issue by taca** [socketry/io-event#93]
io-event 1.4.2 build fails on NetBSD 10.0_RC3/amd64.
selector.c require definition of WNOHANG and including <sys/wait.h> in selector.h solve the problem.

http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/devel/ruby-io-event/patches/patch-ext_io_event_selector_selector.h

**Comment by ioquatix** [comment]
Okay, this is fixed in v1.4.3 - thanks for the report. Please feel free to discuss any other compatibility issues so we can solve them here rather than downstream patching :)
