### ISSUE TITLE
Hanging tests on some platforms

### ISSUE THREAD

**Issue by ahorek** [socketry/io-event#96]
truffleruby, jruby and windows builds hangs here https://github.com/socketry/io-event/blob/main/lib/io/event/selector/select.rb#L173

could it be intentional because of missing WNOHANG support on these platforms? https://github.com/socketry/io-event/pull/95 I'm not familiar with the code around Fibers :)

**Comment by ioquatix** [comment]
Windows is hanging because in general, non-blocking IO on Windows is inconsistently implemented. We probably need to improve the support in CRuby itself and skip the tests that are failing here.

**Comment by ahorek** [comment]
skipping broken tests on Windows is fine for me since I don't have any issues with real apps. I was just concerned about failing CI...

**Comment by ioquatix** [comment]
CI is now passing, except for JRuby and TruffleRuby which have test failures.
